rootProject.name = "SampleProject"
include("kafka-basics")
include("oops-basics")
include("hshmaps")
include("tcp")
include("hashmap")
include("dp")
include("graph")
include("linkedlists")
include("strings")
include("leaderboard")
include("test")
include("walmart")
include("trees")
include("test")
include("practice")
include("binarysearch")
include("designpatterns")
