rootProject.name = "SampleProject"
include("pattern0_intervals")
include("pattern1_binarysearch")
include("pattern2_machinecoding")
include("pattern3_priorityqueues")
include("pattern4_lld")
include("pattern5_multithreading")
include("pattern6_designpatterns")
include("pattern7_hashmaps")
include("pattern8_linkedlists")
include("pattern9_monotonicstack")
include("pattern10_trees")
include("pattern11_dp")
include("pattern12_graphs")
include("pattern13_slidingwindows")
include("pattern14_lru")
include("pattern15_bitwisemanipulation")
include("pattern16_stringmanipulation")

include("kafka-basics")
include("oops-basics")
include("tcp")

include("misc")
include("machinecoding_foodorderingsystem")
include("machinecoding_leaderboard")
include("machinecoding_firstclubmembership")
