rootProject.name = "SampleProject"
include("pattern1_binarysearch")
include("pattern2_machinecoding")
include("pattern3_priorityqueues")
include("pattern4_lld")
include("pattern5_multithreading")
include("pattern6_designpatterns")
include("pattern7_hashmaps")
include("pattern8_linkedlists")

include("misc")
include("kafka-basics")
include("oops-basics")
include("tcp")

include("dp")
include("graph")
include("strings")
include("trees")
include("backtracking")
include("machinecoding_foodorderingsystem")
include("machinecoding_leaderboard")
include("machinecoding_firstclubmembership")
include("stack")
